name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - name: Build Docker Image
       run: sudo docker build -t app .
        
     - name: Log in to Docker Hub
       run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

     - name: Tag Docker Image
       run: docker tag app vivekshaurya/thesocialedge-front
        
     - name: Push Docker Image
       run: docker push vivekshaurya/thesocialedge-front
